/* =========================================================
   HYBRID RECOMMENDATION ENGINE
   Python recommendations + JavaScript fallback
   ========================================================= */

function getRecommendations(limit = 10) {

    /*
     * Prefer recommendations generated by Python.
     */

    if (
        window.StreamBoxAnalytics &&
        window.StreamBoxAnalytics.state &&
        window.StreamBoxAnalytics.state.loaded
    ) {

        const pythonRecommendations =
            window.StreamBoxAnalytics.getRecommendations();

        if (
            pythonRecommendations &&
            pythonRecommendations.length
        ) {
            return pythonRecommendations.slice(
                0,
                limit
            );
        }
    }


    /*
     * JavaScript fallback.
     */

    const watched =
        state.watchHistory || [];

    const genreFrequency = {};

    watched.forEach(item => {

        (item.genres || []).forEach(genre => {

            const normalized =
                String(genre).toLowerCase();

            genreFrequency[normalized] =
                (genreFrequency[normalized] || 0) + 1;
        });

    });


    const favoriteGenres =
        Object.entries(genreFrequency)
            .sort(
                (a, b) =>
                    b[1] - a[1]
            )
            .slice(0, 5)
            .map(
                ([genre]) => genre
            );


    const watchedIds =
        new Set(
            watched.map(
                item => Number(item.id)
            )
        );


    let recommendations = [];


    favoriteGenres.forEach(genre => {

        const matches =
            SB.allContent.filter(item => {

                if (
                    watchedIds.has(
                        Number(item.id)
                    )
                ) {
                    return false;
                }

                return item.genres.some(
                    itemGenre =>
                        String(itemGenre)
                            .toLowerCase() ===
                        genre
                );
            });

        recommendations.push(
            ...matches
        );

    });


    if (!recommendations.length) {

        recommendations =
            SB.getTopRated(20);
    }


    const unique =
        recommendations.filter(
            (item, index, array) =>
                array.findIndex(
                    candidate =>
                        Number(candidate.id) ===
                        Number(item.id)
                ) === index
        );


    return unique
        .sort(
            (a, b) =>
                b.popularity -
                a.popularity
        )
        .slice(
            0,
            limit
        );
}
